BACKUP_MOUNT=/mnt/backup
NEXTCLOUD_PATH=/srv/nextcloud
POSTGRES_DB=nextcloud
POSTGRES_USER=nextcloud

RESTIC_REPOSITORY=/mnt/backup/restic
RESTIC_PASSWORD_FILE=/etc/backup-service/restic.pass

LOG_LEVEL=INFO

NEXTCLOUD_DATA_DIR=/var/snap/nextcloud/common/nextcloud/data
NEXTCLOUD_CONFIG_DIR=/var/snap/nextcloud/current/nextcloud/config