LOG_LEVEL=DEBUG
BACKUP_MOUNT=/mnt/backup
BACKUP_DEVICE_UUID=c2117669-a245-4682-805f-f94f81e27ee1

RESTIC_REPOSITORY=/mnt/backup/restic
RESTIC_PASSWORD_FILE=/etc/backup-service/restic.pass

RESTIC_RETENTION_DAILY=7
RESTIC_RETENTION_WEEKLY=4
RESTIC_RETENTION_MONTHLY=12
RESTIC_CACHE_DIR=/var/cache/backup

NEXTCLOUD_DATA_DIR=/mnt/nas/nextcloud/data
NEXTCLOUD_CONFIG_DIR=/var/snap/nextcloud/current/nextcloud/config

NEXTCLOUD_OCC=/snap/bin/nextcloud.occ
NEXTCLOUD_OCC_TIMEOUT=30

NOTIFIER_DIR=/opt/home-lab
